package application.state;
public enum GameState {
	NEW_GAME,
	NEW_TURN,
	DICED_DRAWABLE,
	DICED_NOT_DRAWABLE_THROWABLE,
	DICED_NOT_DRAWABLE_NOT_THROWABLE,
	DRAWN_NOT_OCCUPIED,
	DRAWN_OCCUPIED,
	SHOW_QUESTION,
	SHOW_ANSWER,
	WAIT_FOR_DONE,
	END_TURN_NORMAL,
	END_TURN_TEST,
	END_GAME
}
